### PR TITLE
A user will see their style at the end of the survey and can redirect…

### LINKED ISSUE #50: Display User style
When the user finishes the survey an API call needs to be made which will return the updated user information. This information will be displayed in the DOM using an `H1` component.

### LINKED ISSUE #51: Fix failing test
After requesting the user's data with the API call, the `web/src/modules/StyleSurvey.test.js` will break.

### PR DESCRIPTION
**Pull request by npdarrington**
What’s this PR do?  
- Displays a user their style based on the survey after clicking submit.
- Removes unnecessary comments.
- Fixes testing files to pass after updates to display user style.
- A user can redirect back to their subscriptions page after finishing their survey.
- Moves the survey data into its own file instead of living directly on StyleSurvey component.
- PropTypes StyleSurvey component.
- Removes any redundancies found in code.
- Clears StyleSurvey values when a user takes a survey and logs out.
 
Where should the reviewer start?  
- git pull this branch.
- web/src/modules/StyleSurvey.
- `npm start` inside web directory to launch FE and BE.
- `npm install` inside web directory if testing dependencies are not installed.
 
How should this be manually tested?  
- login with a user.
- navigate to crates.
- Ensure a user cannot take the survey if they have already taken it (check for true inside DB).
- Change flag to false and click on `+subscribe` to do a survey.
- Finish the survey and test link to subscriptions.
- Finish the survey and ensure you see your style.
- Try to take a survey again with that same user to ensure it doesn't launch twice.
- Log out with that user to ensure any data pertaining to style clears.
 
Any background context you want to provide?  
- n/a
 
What are the relevant tickets?  
- fix #51 
- fix #50 
 
Screenshots (if appropriate)  
 - n/a

Questions: 
- n/a

### CODE REVIEW

File: code/api/src/modules/user/resolvers.js [hunk 1]
```diff
@@ -10,20 +10,25 @@ import models from '../../setup/models'
...
       },
-      { where: { id }}
-    )
+      { where: { id }},
+      )
+    return {
+      id: id,
+      survey: survey,
+      style: key
+    }
```
Comment (Atos20) [inline code/api/src/modules/user/resolvers.js:31]: no wonder we were getting `null` as the returned value. Thanks

File: code/web/src/modules/StyleSurvey/StyleSurvey.js [hunk 2]
```diff
@@ -1,13 +1,15 @@
...
-import { H5, H6 } from '../../ui/typography';
+import { H1, H5, H6 } from '../../ui/typography';
 import { grey, grey2 } from '../../ui/common/colors';
 import { Helmet } from 'react-helmet';
 import { textLevel1 } from '../../ui/common/shadows';
 import { level1, glowShadow } from '../../ui/common/shadows';
 import { messageShow, messageHide } from '../common/api/actions'
-import { withRouter } from 'react-router-dom'
+import userRoutes from '../../setup/routes/user'
+import { Link, withRouter } from 'react-router-dom'
```
Comment (Atos20) [inline code/web/src/modules/StyleSurvey/StyleSurvey.js:12]: Do you know why we need `withRouter` here?

File: code/web/src/modules/StyleSurvey/StyleSurvey.test.js [hunk 3]
```diff
@@ -33,6 +34,12 @@ describe('StyleSurvey component', () => {
 			currentIndex: 0,
             survey: 'athletic'
         }
+
+        styleSurveyData.map(surveyData => {
+            return surveyData.images.map(image => {
+                return image.selected = false;
+            })
+        })
```
Comment (Atos20) [inline code/web/src/modules/StyleSurvey/StyleSurvey.test.js:42]: I like that this is working but I want to know if there is another way of doing this just out of curiosity.

File: code/web/src/modules/user/api/actions.js [hunk 4]
```diff
@@ -92,7 +92,7 @@ export function register(userDetails) {
 export function assignUserStyle(userDetails) {
   return dispatch => {
     dispatch({
-      type: LOGIN_REQUEST,
+      type: ASSIGN_STYLE,
```
Comment (Atos20) [inline code/web/src/modules/user/api/actions.js:95]: Funny enough this was working with the `LOGIN_REQUEST`

**Review by Atos20 — APPROVED** [review]
